### ISSUE TITLE
Documentation and API Examples down

### ISSUE THREAD

**Issue by Potemkinkuliss** [AndreWeiner/flowtorch#15]
Hey I want to test the POD implementation on my TomoPIV data sets and noticed that the documentation is down. It would be great to see some implementation examples! Kind regards

**Comment by AndreWeiner** [comment]
Hi @Potemkinkuliss,
thanks for your feedback and interest. flowTorch is still under development and I haven't yet added sufficient examples to the documentation to publish it. It is currently planned to publish the first version in April. I'll mention this issue once the documentation is complete and online (could be also before April). In case you're still interested, can you tell me the PIV data's format?
Best, Andre

**Comment by Potemkinkuliss** [comment]
Hi @AndreWeiner 
thank you for your quick response. Our in-house code produces ascii or netCDF. The Ascii format is pretty straight forward:

```
    1 TITLE = "Displacement vectors in voxel (number of volume = 1)"
    2 VARIABLES = "X", "Y", "Z", "dX", "dY", "dZ", "corr"
    3 ZONE I=59, J=29, K=29 F=Point
    4 8.166667 8.166667 8.166667 -0.036165 0.262408 2.284524 0.574830 
    5 16.500000 8.166667 8.166667 1.815855 0.400456 1.222406 0.586513 
    6 24.833333 8.166667 8.166667 1.432361 -2.095019 1.207039 0.686344 
    7 33.166667 8.166667 8.166667 -0.141117 1.312343 0.295845 0.693353
```


X,Y,Z are the grid locations. _dX, dY, dZ_ are the pixel displacements  and _coor_ indicates the correlation coefficients.
Some grid locations do not have valid vectors. So in these cases they get a NaN value assigned. 
Most algorithms cannot  handle these values, defective sites are often replaced using the median value of neighboring values.
Since I am currently exploring my data I rely on numpy arrays (7,59,29,29,N) with N the numbers of frames.

It would be great to have an open, tested, citeable and non proprietary licensed evaluation tool!  
When I am finished analyzing PDFs I will give it a try and provide feedback.

Best, Alex

**Comment by AndreWeiner** [comment]
Hi Alex,

flowTorch has several `Dataloader` classes providing uniform access to different data formats. It should be only a small effort to add another dataloader for tabular data as you have it. I already have it on my TODO list since most PIV data comes in that kind of format.

Maybe we could even consider adding a tutorial based on your voxel data to the collection of examples (based on data that can be put out in the public domain without any trouble). Let's think about that.

>It would be great to have an open, tested, citeable and non proprietary licensed evaluation tool!
When I am finished analyzing PDFs I will give it a try and provide feedback.

Great to hear. My supervisor, @rsemaan, and I think so too.

Best, Andre
